
export const SEARCH_REQUEST = "SEARCH_REQUEST"
export const SEARCH_FAILURE = "SEARCH_FAILURE"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_HEADER = "SEARCH_HEADER"
export const SEARCH_CATEGORY_CHANGE = "SEARCH_CATEGORY_CHANGE"


export const FETCH_TOP_SALES = "FETCH_TOP_SALES"

// для запросов топ продаж
export const TOPSALES_REQUEST = 'TOPSALES_REQUEST';
export const TOPSALES_SUCCES = 'TOPSALES_SUCCES';
export const TOPSALES_FAILURE = 'TOPSALES_FAILURE';

// для запроса каталога
export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_SUCCES = 'CATALOG_SUCCES';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';
export const CATALOG_CATEGORIES_CHANGE = 'CATALOG_CATEGORIES_CHANGE';

// для запроса категорий
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCES = 'CATEGORIES_SUCCES';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_CHANGE = 'CATEGORIES_CHANGE';

// для запроса offset
export const OFFSET_REQUEST = 'OFFSET_REQUEST';
export const OFFSET_SUCCES = 'OFFSET_SUCCES';
export const OFFSET_FAILURE = 'OFFSET_FAILURE';
export const OFFSET_CHANGE = 'OFFSET_CHANGE';
export const OFFSET_CATEGORIES_CHANGE = 'OFFSET_CATEGORIES_CHANGE';
export const OFFSET_SEARCH_CHANGE = 'OFFSET_SEARCH_CHANGE';

// для запросов продукта
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

// для корзины
export const CART_QUANTITY = 'CART_QUANTITY';

